server:
  port: 8082

spring:
  application:
    name: workout
  datasource:
    url: jdbc:mysql://192.168.101.15:3306/mk-swcenter?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: swcenter
    password: 123456
    encoding: UTF-8
  redis:
    database: 0
    host: 192.168.101.15
    port: 9000
    max-wait: 30000
    max-active: 100
    max-idle: 20
    min-idle: 2

mybatis:
    mapper-locations: classpath:mapper/*.xml
feign:
  hystrix:
    enabled: true

