spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          lowerCaseServiceId: true
          enabled: true
      routes:
        - id: ucenter-router
          uri: lb://ucenter
          predicates:
            - Path=/ucenter/**
          filters:
            - PreserveHostHeader
        - id: workout-router
          uri: lb://workout
          predicates:
            - Path=/workout/**


